fiapweb2020/Controllers/HomeController.cs
using fiapweb2020.core.Models;
using fiapweb2020.core.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace fiapweb2020.Controllers
{
    public class HomeController : Controller
    {
        private INoticiaService _noticiaService;

        public HomeController(INoticiaService noticiaService)
        {
            _noticiaService = noticiaService;
        }


        //public ActionResult Index()
        //public ViewResult Index()
        public IActionResult Index()
        {
            ViewData["Nome"] = "Anderson <script> alert('oi te hackeei'); </script>";
            ViewBag.NomeDaAula = "ASP.NET";

            var pessoa = new Pessoa
            {
                Id = 123,
                Nome = "Tonho"
            };

            //return View("Pagina");
            //return View("Pagina",pessoa);
            return View(pessoa);
        }

        [HttpPost]
        public string Index(Pessoa pessoa)
        {
            return "olá";
        }

        public IActionResult Redir(string redirectUrl)
        {
            return LocalRedirect(redirectUrl);

            //if (Url.IsLocalUrl(redirectUrl))
            //{
            //    return Redirect(redirectUrl);
            //}
         
            //return Redirect("/");
        }

        public IActionResult Teste()
        {


            return View();
        }


        public IActionResult Error()
        {

            //new ErrorViewModel
            //{ RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier }

            return View();
        }
    }
}

fiapweb2020/ViewComponents/NoticiasViewComponent.cs
using fiapweb2020.core.Models;
using fiapweb2020.core.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace fiapweb2020.ViewComponents
{
    public class NoticiasViewComponent : ViewComponent
    {
        private INoticiaService _service;

        public NoticiasViewComponent(INoticiaService service)
        {
            _service = service;
        }

        public async Task<IViewComponentResult> InvokeAsync(int totalDeNoticias, bool noticiasUrgents)
        {
            var view = noticiasUrgents ? "noticiasUrgentes" : "noticias";

            //await Task.Delay(200);
            return View(view, _service.Load(totalDeNoticias));
        }
    }
}

fiapweb2020/Views/Home/Index.cshtml
@model fiapweb2020.core.Models.Pessoa

<h1>
    @*@Html.Raw(ViewData["Nome"])*@
    @ViewData["Nome"]
</h1>
<h2>
    Boa noite
</h2>
<div class="row">
    <div id="carroseul" class="col">
        <div class="jcarousel-wrapper">
            <div class="jcarousel">
                <ul>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-1.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-2.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-3.jpg" />
                    </li>
                    <li>
                        <img class="carroseulimage" src="~/images/imagem-4.jpg" />
                    </li>
                </ul>
            </div>
            <div>
                <a href="#" class="jcarousel-control-prev">&lsaquo;</a>
                <a href="#" class="jcarousel-control-next">&rsaquo;</a>
            </div>
            <div>	    </div>

        </div>
    </div>
</div>


<div class="row">
    <div id="menu">
        <ul>
            <li>
                <div class="icon paises brasil"></div>
                @*<img class="icon" src="~/images/brasil.png" />*@
                Brasil
            </li>
            <li>
                <div class="icon paises alemanha"></div>

                Alemanha
            </li>
            <li>
                <div class="icon paises grecia"></div>

                Grecia
            </li>
            <li>
                <div class="icon paises eua"></div>

                EUA
            </li>
            <li>
                <div class="icon paises canada"></div>

                Canada
            </li>
            <li>
                <div class="icon paises argentina"></div>
                Argentina
            </li>
            <li>
                <div class="icon paises japao"></div>

                Japão
            </li>
            <li>
                <div class="icon paises italia"></div>

                Italia
            </li>
            <li>
                <div class="icon paises espanha"></div>

                Espanha
            </li>
            <li>
                <div class="icon paises portugal"></div>
                Portugal
            </li>
        </ul>
    </div>
</div>




@*<h1>Hello @ViewData["Nme"] </h1>
    <h2>@ViewBag.NomeDaAula</h2>
    <h2>@Model.Nome</h2>

    <email mail-to="cadu"></email>

    <br />
    <img src="~/giphy.webp" asp-append-version="true" />*@


@*@foreach (var item in Model.Produtos)
    {
        @await Html.PartialAsync("_Detalhe", item)

    }*@



@*@section Footer{
        <div>Meu footer</div>
    }*@

<div class="row">
    <div class=" col">
        <vc:noticias noticias-urgents="true" total-de-noticias="5"></vc:noticias>
    </div>
</div>


@*<script src="https://code.jquery.com/jquery-3.3.1.min.js"
            integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
            crossorigin="anonymous"></script>
    <script type="text/javascript">
        $.get("https://localhost:5001/api/clientes/", function (data, status) {
            console.log("Data: " + data);
        });
    </script>*@